[webui_ips] # IPs to the instances of automatic webui
webui1 = 'http://127.0.0.1:7860/'

[ratelimit_roles] # gens per hour per role, set to -1 to disable ratelimit
DEFAULT = -1 # ratelimit if no other ratelimit role is found
# RATE LIMITS DO NOT WORK CURRENTLY

[dm_access_roles] # roles that have DM access perms
ALL = false # gives all users DM access
# PER ROLE DM ACCESS DOESN'T WORK CURRENTLY

[command_params]
default_negative = 'score_4, score_5, score_6,  score_3, score_2, score_1, simple background, lowres, low detail, blurry, watercolor, muscular female, bad anatomy, bad proportions, deformed, deformed anatomy, deformed fingers,logo,text,english text,patreon username,patreon logo, deformed anatomy,deformed fingers,monochrome,photo,hyperrealistic,realstic,skinny,rough sketch,fewer digits,extra digits,signature,artist name,mosaic,missing fingers,3d,too many fingers,mutated hands, source_pony, source_furry, source_cartoon,bad hands, worst quality, low quality, extra legs, deformed anatomy, messy color, 3d, distracted, jpeg artifacts, comic'
default_cfg = 7

default_width = 896
min_width = 512
max_width = 1664

default_height = 1152
min_height = 512
max_height = 1408

default_steps = 25
min_steps = 5
max_steps = 50
step_step = 5

samplers = [
            'Euler a', 'Euler', 'LMS', 'Heun', 'DPM2', 'DPM2 a', 'DPM++ 2S a', 'DPM++ 2M', 'DPM++ SDE', 'DPM fast',
            'DPM adaptive', 'LMS Karras', 'DPM2 Karras', 'DPM2 a Karras', 'DPM++ 2M Karras', 'DPM++ SDE Karras',
            'DDIM', 'PLMS'
        ]
models = ['abyssorangemix3AOM3_aom3a3.safetensors [eb4099ba9c]', 'deliberate_v11.safetensors [d8691b4d16]', 'nai.ckpt [89d59c3dde]']

default_sampler = 'Euler a'

[blacklist] # blacklisted generation words
words = []
allow_in_negative = true # allow blacklisted words in negative prompt
