prefix = 'h!'
mod_role_ids = [1176210082585919570, 1229109645134663690, 1216850704791244914, 1178585102746394666]
owner_id = 723815216701505606

[webui_ips] # IPs to the instances of automatic webui
webui1 = 'http://127.0.0.1:7860/'

[command_params]
default_negative = 'score_4, score_5, score_6,  score_3, score_2, score_1, simple background, lowres, low detail, blurry, watercolor, muscular female, bad anatomy, bad proportions, deformed, deformed anatomy, deformed fingers,logo,text,english text,patreon username,patreon logo, deformed anatomy,deformed fingers,monochrome,photo,hyperrealistic,realstic,skinny,rough sketch,fewer digits,extra digits,signature,artist name,mosaic,missing fingers,3d,too many fingers,mutated hands, source_pony, source_furry, source_cartoon,bad hands, worst quality, low quality, extra legs, deformed anatomy, messy color, 3d, distracted, jpeg artifacts, comic'
default_cfg = 3

default_ratio = '7:9'

default_steps = 14
min_steps = 5
max_steps = 30

samplers = [
            'Euler a', 'Euler', 'LMS', 'Heun', 'DPM2', 'DPM2 a', 'DPM++ 2S a', 'DPM++ 2M', 'DPM++ SDE', 'DPM fast',
            'DPM adaptive', 'LMS Karras', 'DPM2 Karras', 'DPM2 a Karras', 'DPM++ 2M Karras', 'DPM++ SDE Karras',
            'DDIM', 'PLMS'
        ]
models = ['']

default_sampler = 'Euler a'

[blacklist] # blacklisted generation words
words = ['loli', 'shota', 'child', 'children']

nsfw_channels = ['1249359906746929254']
nsfw_words = ['nsfw', 'nude', 'naked', 'pussy', 'vagina', 'dick', 'cock', 'penis', 'creampie', 'cum', 'erection', 'ejaculation', 'sex', 'vaginal', 'milf', 'ahegao', 'nipples']

allow_in_negative = true # allow blacklisted words in negative prompt

[aspect_ratios]
'1:2' = [704, 1408]
'11:21' = [704, 1344]
'4:7' = [768, 1344]
'3:5' = [768, 1280]
'13:19' = [832, 1216]
'13:18' = [832, 1152]
'7:9' = [896, 1152]
'14:17' = [896, 1088]
'15:17' = [960, 1088]
'1:1' = [1024, 1024]
'15:16' = [960, 1024]
'17:15' = [1088, 960]
'17:14' = [1088, 896]
'9:7' = [1152, 896]
'18:13' = [1152, 832]
'19:13' = [1216, 832]
'5:3' = [1280, 768]
'7:4' = [1344, 768]
'21:11' = [1344, 704]
'2:1' = [1408, 704]
'23:11' = [1472, 704]
'12:5' = [1536, 640]
'5:2' = [1600, 640]
'26:9' = [1664, 576]

[template]
'Frieren' = '/generate prompt: 1girl, (masterpiece:1.3), (high resolution), (8K), (extremely detailed), (4k), (pixiv), perfect face, nice eyes and face, (best quality), (super detailed), detailed face and eyes, (solo), textured skin, absurdres, highres, <lora:Frieren:0.8>, frieren, twintails, very long hair, silver hair, pointy ears, elf, white capelet, green eyes, black pantyhose, earrings, white skirt, belt, white sleeves, pov, light, smile, light rays, sunlight, butterfly, grass, stone street'
'Mikasa Ackerman' = '/generate prompt: score_9, score_8_up, score_7_up, score_6_up, score_5_up, score_4_up, BREAK, (minakami style), BREAK, 1girl, black hair, mikasa ackermann, mikasa ackerman, <lora:mikasa:0.9> mikaackermanSDXL, gray_eyes, portrait, village steps: 8'
'Levi Ackerman' = '/generate prompt:score_9, score_8_up, score_7_up, source_anime, rating_safe, intricate details, anime screencap, anime coloring, 1boy, solo, male focus, <lora:levi_ackerman_pony:0.9>, levi_ackerman, black hair, black eyes, short hair, curtained hair, final season, asymmetrical, niagara falls, indoors, light, arm support, expressionless'
'Eren Yeager' = '/generate prompt: score_9, score_8_up, score_7_up, source_anime, rating_safe, intricate details, anime screencap, official style, looking at viewer, , 1boy, solo, male focus, <lora:eren_yeager_s4_pony:1>, eren_yeager_s4, brown hair, blue eyes, medium hair, from above, ancient ruins, day, clouds, arm support, giggling, trench coat steps: 8'
'Armin Arlert' = '/generate prompt: score_9, score_8_up, score_7_up, source_anime, rating_safe, (3d:0.4), 1boy, solo, male focus, <lora:armin_arlert_pony:0.84>, armin_arlert, blonde hair, blue eyes, short hair, bob cut, bangs, from above, full body, flower field, flowers, noon, arms behind back, light smile steps: 10'
'Armin Arlert 2' = '/generate prompt: score_9, score_8_up, score_7_up, source_anime, rating_safe, intricate details, (photorealistic:0.6), looking at viewer, 1boy, solo, male focus, <lora:armin_arlert_pony:0.88>, armin_arlert, blonde hair, blue eyes, very short hair, bowl cut, wide angle, wide shot, cowboy shot, store, convenience store, day, arms behind back, sad steps: 11 guidance_scale: 2.5'
'Ymir Fritz' = '/generate prompt: score_9, score_8_up, score_7_up, BREAK source_anime, <lora:Ymir Fritz-PonyXL-lora-faxtron:0.8> ymir fritz, blue eyes, blonde hair, long hair, medium breasts, armlet, bare shoulders, hairband, long white tunic'
'Annie Leonhart' = '/generate prompt:score_9, score_8_up, score_7_up, BREAK source_anime, <lora:annie leonhardt-PonyXL-lora-Faxtron:0.8> annie leonhardt, single hair bun, white hoodie, open cropped brown jacket, white pants, thigh strap, survey corps \(emblem\), knee boots'
'Sasha Braus' = '/generate prompt:score_9, score_8_up, score_7_up, BREAK source_anime, <lora:Sasha Blouse-PonyXL-lora-Faxtron:0.8> sasha blouse, brown eyes, brown hair, short ponytail, medium breasts, black pants, boots'
