[webui_ips] # IPs to the instances of automatic webui
webui1 = 'http://127.0.0.1:7860/'

[command_params]
default_negative = 'score_4, score_5, score_6,  score_3, score_2, score_1, simple background, lowres, low detail, blurry, watercolor, muscular female, bad anatomy, bad proportions, deformed, deformed anatomy, deformed fingers,logo,text,english text,patreon username,patreon logo, deformed anatomy,deformed fingers,monochrome,photo,hyperrealistic,realstic,skinny,rough sketch,fewer digits,extra digits,signature,artist name,mosaic,missing fingers,3d,too many fingers,mutated hands, source_pony, source_furry, source_cartoon,bad hands, worst quality, low quality, extra legs, deformed anatomy, messy color, 3d, distracted, jpeg artifacts, comic'
default_cfg = 3

default_ratio = '7:9'

default_steps = 14
min_steps = 5
max_steps = 30

samplers = [
            'Euler a', 'Euler', 'LMS', 'Heun', 'DPM2', 'DPM2 a', 'DPM++ 2S a', 'DPM++ 2M', 'DPM++ SDE', 'DPM fast',
            'DPM adaptive', 'LMS Karras', 'DPM2 Karras', 'DPM2 a Karras', 'DPM++ 2M Karras', 'DPM++ SDE Karras',
            'DDIM', 'PLMS'
        ]
models = ['abyssorangemix3AOM3_aom3a3.safetensors [eb4099ba9c]', 'deliberate_v11.safetensors [d8691b4d16]', 'nai.ckpt [89d59c3dde]']

default_sampler = 'Euler a'

[blacklist] # blacklisted generation words
words = ['loli', 'shota', 'child', 'children']

nsfw_channels = ['1249359906746929254']
nsfw_words = ['nsfw', 'nude', 'naked', 'pussy', 'vagina', 'dick', 'cock', 'penis', 'creampie', 'cum', 'erection', 'ejaculation', 'sex', 'vaginal', 'milf', 'ahegao', 'nipples']

allow_in_negative = true # allow blacklisted words in negative prompt

[aspect_ratios] # Image Aspect Ratios
'1:2' = [704, 1408]
'11:21' = [704, 1344]
'4:7' = [768, 1344]
'3:5' = [768, 1280]
'13:19' = [832, 1216]
'13:18' = [832, 1152]
'7:9' = [896, 1152]
'14:17' = [896, 1088]
'15:17' = [960, 1088]
'1:1' = [1024, 1024]
'15:16' = [960, 1024]
'17:15' = [1088, 960]
'17:14' = [1088, 896]
'9:7' = [1152, 896]
'18:13' = [1152, 832]
'19:13' = [1216, 832]
'5:3' = [1280, 768]
'7:4' = [1344, 768]
'21:11' = [1344, 704]
'2:1' = [1408, 704]
'23:11' = [1472, 704]
'12:5' = [1536, 640]
'5:2' = [1600, 640]
'26:9' = [1664, 576]